### ISSUE TITLE
error when running generate_common-snps.py

### ISSUE THREAD

**Issue by Colin-Cheng** [greenelab/tad_pathways#31]
I was running generate_common-snps.py and got the following error in vcf.reader:

Traceback (most recent call last):
  File "scripts/generate_common-snps.py", line 114, in <module>
    for r in vcf.Reader(filename=path):
  File "/Users/chengw1/miniconda3/envs/tad_pathways/lib/python3.5/site-packages/vcf/parser.py", line 565, in __next__
    filt = row[6]
IndexError: list index out of range

**Comment by gwaybio** [comment]
Thanks @Colin-Cheng - can you provide more context with your error?

To me, it looks like an issue with the input file provided on [line 114](https://github.com/greenelab/tad_pathways/blob/master/scripts/generate_common-snps.py#L114). Which file is causing this issue? I would check if it downloaded correctly.

**Comment by Colin-Cheng** [comment]
/data/hg/subsetvcf/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz, this is the file causing the issue.

**Comment by gwaybio** [comment]
was it downloaded completely? Can you confirm that the `md5sum` is`3cd5dcf574f4bd5c95c508f18928b145`?

**Comment by gwaybio** [comment]
Also, what version of `PyVCF` are you using?

**Comment by Colin-Cheng** [comment]
I don't have `md5sum` installed. But `md5 -r ` gives `94762c812c7c80f0a59b8b27c3b7fa9c`.
And I am using the version in environment.yml: - PyVCF==0.6.8

**Comment by gwaybio** [comment]
i can only confirm correct download with the md5sum I provided above

I recommend performing some more troubleshooting to solve. Note that this project is deprecated and support may be a bit delayed. Although, I would love to get this TAD index file generation cleaned up.

Once you find the error, please report back in this issue and/or file a pull request to make changes. Thanks again!

**Comment by Colin-Cheng** [comment]
I think the problem is that I didn't fully download the file. Thank you!
